### ISSUE TITLE
Consider naming `config` folder to `webpack`

### ISSUE THREAD

**Issue by aburd** [WWK563388548/line-miniapp-starter#1]
Config makes me think of configurable settings to the project itself, rather than just webpack transpilation.

**Comment by aburd** [comment]
@WWK563388548

**Comment by WWK563388548** [comment]
@aburd 
I agree.
I'll fix it later.

**Comment by WWK563388548** [comment]
@aburd 
I've renamed the webpack folder

**Comment by aburd** [comment]
Very niceeeeee!
I'll closed this then. Heh.
