### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by aburd** [WWK563388548/line-miniapp-starter#2]
I think it's best to make all of our projects Typescript to help with bugs and development.
This could present somewhat of an issue with the LINE related libraries, but perhaps we can add d.ts files. This might also help  people to understand how their libraries work.

**Comment by aburd** [comment]
@WWK563388548

**Comment by WWK563388548** [comment]
@aburd 
This project is in WIP status, but TS support will definitely be added later!!!

**Comment by aburd** [comment]
When would you add it?

**Comment by WWK563388548** [comment]
@aburd 
From tonight or tomorrow

**Comment by WWK563388548** [comment]
@aburd 
I've added the Typescript support.

**Comment by aburd** [comment]
それではこれを閉じますね！
